config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  devise_for :users
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friends', to: 'users#search'
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true
  def self.new_lookup(ticker_symbol)
      client = IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
      endpoint: 'https://sandbox.iexapis.com/v1'
      )
      begin
        new(ticker: ticker_symbol , name: client.company(ticker_symbol).company_name , last_price: client.price(ticker_symbol))
      rescue => exception
        return nil
      end
  end
  def self.check_db(ticker)
    where(ticker: ticker).first
  end

end


# Rails.application.credentials.iex_client[:sandbox_api_key]

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def already_tracked(ticker)
    stock = Stock.check_db(ticker)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end
  def track_limit
    stocks.count < 10
  end
  def can_track(ticker)
    return track_limit && !already_tracked(ticker)
  end
  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous"
  end
  def self.first_name_matches(param)
    matches('first_name', param)
  end
  def self.last_name_matches(param)
      matches('last_name', param)
  end
  def self.email_matches(param)
      matches('email', param)
  end
  def self.search(param)
    param.strip!
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end
  def except_current_user(users)
    users.reject {|user| user.id == self.id}
  end
  def self.matches(field, param)
    where("#{field} like ?", "%#{param}%")
  end
  def not_friends_with(user)
    !self.friends.where(id: user).exists?
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    user = User.find(params[:user])
    current_user.friendships.build(friend_id: user.id)
    if current_user.save
      flash[:notice] = "#{user.first_name} followed"
      redirect_to my_friends_path
    end
  end

  def destroy
    friendship = current_user.friendships.where(friend_id: params[:id]).first
    friendship.destroy
    flash[:notice] = "friend unfollowed"
    redirect_to my_friends_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      if @stock
        respond_to do |response|
          response.js {render partial: 'users/result'}
        end
      else
        respond_to do |response|
          flash.now[:alert] = 'please enter a valid stock or check the connection'
          response.js {render partial: 'users/result'}
        end
      end
    else
      respond_to do |response|
        flash.now[:alert] = "please enter a symbol to search"
        response.js {render partial: 'users/result'}
      end
    end

  end

end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock = Stock.check_db(params[:ticker])
    if stock.blank?
      stock = Stock.new_lookup(params[:ticker])
      stock.save
    end
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:notice] = "stock #{stock.name} saved..."
    redirect_to my_portfolio_path

  end
  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(user: current_user, stock: stock).first
    user_stock.destroy
    flash[:notice] = "stock untracked successfulyl :)"
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user = current_user
    @stocks = current_user.stocks
  end
  def my_friends
    @friends = current_user.friends
  end
  def search
    if params[:friend].present?
      @friends = User.search(params[:friend])
      @friends = current_user.except_current_user(@friends)
      if @friends
        respond_to do |response|
          response.js {render partial: 'users/friend_result'}
        end
      else
        respond_to do |response|
          flash.now[:alert] = 'couldn`t find user'
          response.js {render partial: 'users/friend_result'}
        end
      end
    else
      respond_to do |response|
        flash.now[:alert] = "please enter a name or an email to search"
        response.js {render partial: 'users/friend_result'}
      end
    end
  end
  def show
    @user = User.find(params[:id])
    @stocks = @user.stocks
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friends/_friends_list.html.erb
<div class="row">
  <div class="col-9">
    <table class="table table-hover table-bordered table-dark mt-2">
      <thead>
        <tr>
          <th scope="col">Email</th>
          <th scope="col">First Name</th>
          <th scope="col">Last Name</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @friends.each do |friend| %>
          <tr>
            <td><%= friend.email %></td>
            <td><%= friend.first_name %></td>
            <td><%= friend.last_name %></td>
            <td><%= link_to 'unfollow', friendship_path(friend), method: :delete, data: {confirm: "sure??!!"}, class: "btn btn-sm  btn-danger" %>
              <%= link_to 'view profile', user_path(friend), class: "btn btn-sm  btn-danger" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/_message.js.erb
setTimeout(function(){
  $('#message').fadeOut();
}, 2000);

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
  <% if message_type == 'error' %>
    <div class="alert alert-danger" id="message">
        <%= message_content %>
    </div>
  <% else %>
    <div class="alert alert-success" id="message">
        <%= message_content %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
        <%= link_to 'Stock Tracker', root_path, class: "navbar-brand" %>
        <% if current_user %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item <%= 'active' if request.path == my_portfolio_path %>">
                <%= link_to "my portfolio", my_portfolio_path, class: "nav-link" %>
              </li>
              <li class="nav-item <%= 'active' if request.path == my_friends_path %>">
                <%= link_to "my friends", my_friends_path, class: "nav-link" %>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  profile
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to 'Edit', edit_user_registration_path, class:"dropdown-item" %>
                  <a class="dropdown-item" href="#">Another action</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>
              </li>
            </ul>
            <ul class="navbar-nav ml-auto">
              <li class="nav-item mr-1 mt-1 ">
                <%= current_user.full_name %>
              </li>
              <li class="nav-item">
                <%= link_to 'Log Out', destroy_user_session_path, class: "btn btn-danger btn-sm mr-1", method: :delete %>
              </li>
            </ul>

            <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
          </div>
        <% end %>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/stocks/_stocks.html.erb
<div class="row">
  <div class="col-9">
    <table class="table table-hover table-bordered table-dark mt-2">
      <thead>
        <tr>
          <th scope="col">Stock</th>
          <th scope="col">Name</th>
          <th scope="col">Price</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @stocks.each do |stock| %>
          <tr>
            <td><%= stock.ticker %></td>
            <td><%= stock.name %></td>
            <td><%= stock.last_price %></td>
            <td>
              <% if current_user.can_track(stock.ticker) %>

                <%= link_to 'Add to portfo', user_stocks_path(user: current_user, ticker: stock.ticker),
                                                          class: "btn btn-success btn-sm", method: :post %>
              <% elsif current_user.id != @user.id %>
                <span class="badge badge-primary">
                  tracking
                  <% if !current_user.track_limit %>
                    10 stocks hit
                  <% end %>
                </span>
              <% end %>
               <% if current_user.id == @user.id %>
                    <%= link_to 'Utrack', user_stock_path(stock), method: :delete, data: {confirm: "sure??!!"}, class: "btn btn-sm  btn-danger" %>
                <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/_friend_result.html.erb
<% if @friends %>
<div class="card card-header w-50 d-block">
  <table>
    <tbody>
      <% @friends.each do |friend| %>
            <tr>
              <td><strong>Name: <%= friend.first_name %></strong>  </td>
              <td class="ml-1"><strong> Email: <%= friend.email %></strong>  </td>
              <td class="ml-1"><strong> profile: <%= link_to 'view profile', user_path(friend), class:"btn btn-success btn-sm" %></strong>
                <% if current_user.not_friends_with(friend.id) %>
                  <%= link_to 'follow', friendships_path(user: friend),class: "btn btn-success btn-sm", method: :post %>
                <%else%>
                  <span class="badge badge-primary">friends</span>
                <%end%>
            </td>
            </tr>
      <% end %>
    </tbody>
  </table>

</div>
<%end%>
<div class="w-25" id="message">
    <%= render 'layouts/messages' %>
</div>

app/views/users/_friend_result.js.erb
document.getElementById('results').innerHTML = '<%= j render 'users/friend_result.html' %>'

app/views/users/_result.html.erb
<% if @stock %>
  <div class="card card-header w-25">
    <strong>Symbol: <%= @stock.ticker %></strong>
    <strong>Name: <%= @stock.name %></strong>
    <strong>Last Price: <%= @stock.last_price %></strong>
    <% if current_user.can_track(@stock.ticker) %>

      <%= link_to 'Add to portfo', user_stocks_path(user: current_user, ticker: @stock.ticker),
                                                class: "btn btn-success btn-sm", method: :post %>
    <% else %>
      <span class="badge badge-primary">
        tracking
        <% if !current_user.track_limit %>
          10 stocks hit
        <% end %>
      </span>
    <% end %>
  </div>
<%end%>
<div class="w-25" id="message">
    <%= render 'layouts/messages' %>
</div>

app/views/users/_result.js.erb
document.getElementById('results').innerHTML = '<%= j render 'users/result.html' %>'

app/views/users/my_friends.html.erb
<h1>Friend</h1>
<div class="search-area">
  <h3 class="mt-5">search friends</h3>

  <%= form_tag search_friends_path, remote: true,  method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 pr-0">
        <%= text_field_tag :friend, params[:friend] ,placeholder: 'friend search', autofocus: true, class: "form-control form-control-large input" %>
      </div>
      <div class="col-sm-3 pl-0">
        <%= button_tag type: :submit, class: "btn btn-success " do %>
          <%= 'search' %>
        <%end%>
      </div>
    </div>

  <%end%>
</div>
<div id="results">

</div>
<% if !@friends.empty? %>
  <%= render 'friends/friends_list' %>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>my portfolio</h1>

<div class="search-area">
  <h3 class="mt-5">search stocks</h3>

  <%= form_tag search_stock_path, remote: true,  method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 pr-0">
        <%= text_field_tag :stock, params[:stock] ,placeholder: 'stock to search', autofocus: true, class: "form-control form-control-large input" %>
      </div>
      <div class="col-sm-3 pl-0">
        <%= button_tag type: :submit, class: "btn btn-success " do %>
          <%= 'search' %>
        <%end%>
      </div>
    </div>

  <%end%>
</div>
<div id="results">

</div>
<% if !@stocks.empty? %>
  <%= render 'stocks/stocks' %>
<% end %>

app/views/users/show.html.erb
<h2>User Details</h2>
<div class="card card-header w-50 d-block">
  <table>
    <tbody>
            <tr>
              <td><strong>Name: <%= @user.first_name %></strong>  </td>
              <td class="ml-1"><strong> Email: <%= @user.email %></strong>  </td>
              <td class="ml-1">
                <% if current_user.not_friends_with(@user.id) %>
                  <%= link_to 'follow', friendships_path(user: @user),class: "btn btn-success btn-sm", method: :post %>
                <%else%>
                  <span class="badge badge-primary">friends</span>
                <%end%>
            </td>
            </tr>
    </tbody>
  </table>

</div>

<% if !@stocks.empty? %>
  <%= render 'stocks/stocks' %>
<% else %>
  <p class="lead">"#{@user.first_name} is not tracking any stocks"</p>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to stock tracker</h1>